PedroBern/react-native-collapsible-tab-view

- example/package.json
- example/yarn.lock
- package-lock.json
- package.json
- src/CollapsibleTabView.tsx
What was happening was that `onScrollEndDrag` was calling `syncScrollOffset` when the user lifts the finger off the screen, but `onMomentumScrollBegin/onMomentumScrollEnd` is called immediately after and calls the same function. Since the function initiates its own scrolling, there's a loop of events going on.
See https://reactnative.dev/docs/scrollview#onscrollenddrag
> Called when the user stops dragging the scroll view and it either stops **or begins to glide.**
This PR adds a debounce effect so that it is only called once, and it should solve any performance issues without requiring to use `snapToOffsets`.
Will add a screen recording below.
> fix: snapping when momentum scrolling

- .github/workflows/expo-preview.yml
- README.md
- example/src/App.tsx
- example/src/CollapsibleTabViewSmallContentExample.tsx
- example/src/Shared/Albums.tsx
- src/types.ts
- src/useCollapsibleScene.tsx
Add a new example of how to handle small content.
Related: #8
> fix: remove minHeight from contentContainerStyle and add example of small content

- src/createCollapsibleTabs.tsx
- src/types.ts
An alternative to #65.
@andreialecu, I didn't test it (I can't), but what you think?
Instead of using setTimeout, I handled everything on the UI, can you run the preview to see if it has the same behavior as your initial fix, please?
Also, having `isGliding.value=true` before `isScrolling.value=false` ensures we sync tabs **after** the snap, [because of here](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/src/createCollapsibleTabs.tsx#L581).
Close #59
> Fix ios behaviour (2)

- src/MaterialTabBar/Indicator.tsx
- src/createCollapsibleTabs.tsx
- src/types.ts
an alternative to #69 
@alexpchin  what you think?
Close #72
Close #68
[documentation](https://reactjs.org/docs/react-api.html#reactchildrentoarray)
```jsx
// add unique key to each child
React.Children.toArray(children)
```
> Fix ensure array children

- src/createCollapsibleTabs.tsx
- src/types.ts
Fixes #66 
Open for discussion. I didn't notice any breakage from doing it this way.
The idea behind it is that if we detect `onScroll` being called, then we set `isScrolling` to `1`. Once `onScroll` stops firing then it is set back to `0`.
This has the benefit and side effect that other types of scroll besides those initiated by `onBeginDrag` are handled by default (such as programatic scrolls)
> fix: handle scroll to top ios

- README.md
- src/MaterialTabBar/TabBar.tsx
- src/MaterialTabBar/TabItem.tsx
- src/MaterialTabBar/types.ts
- yarn.lock
Hey, this is based mostly on the approach that react-native-tab-view takes about styling their tab bar, the idea is to allow customization without having to refactor/copy the existent bar.
I had to increase the package version because of the following error coming from interpolateColor
https://github.com/software-mansion/react-native-reanimated/issues/1401
Let me know if this changes make sense
Closes #82
> feat: allow tab bar customization

- README.md
- example/src/App.tsx
- example/src/MinHeaderHeight.tsx
- src/createCollapsibleTabs.tsx
- src/types.ts
Hey @PedroBern, this allows to configure a height for the header when collapsed, in other words, the header will be considered collapsed once we reach, header height - collapsed height, I tested all the examples and they seem to be working properly, so I believe I got all the right variables in their place, but if you can give a new look, since you know the project/behavior better than me
Closes #5
> feat: add support for collpased header height

- src/hooks.tsx
> fix: tab sync on ios when scrolling to the top

- src/FlatList.tsx
- src/ScrollView.tsx
- src/hooks.tsx
This delays handling scroll events until after the scroll controls are mounted.
Otherwise we receive a scroll event for the initial scroll position (via `contentOffset`), and this can create a race condition with the scroll position jumping around.
> fix: switching lazy tabs sometimes jumps scroll position on ios

- src/hooks.tsx
`scrollTo` was not in the dependency array, so updates to the `contentInset` value would not properly propagate to it, resulting in wrong scroll sync positions if the `headerHeight` property was not provided.
> fix: add missing hook dependency

- src/Container.tsx
- src/hooks.tsx
We need to wait for the header height to be available, otherwise contentInset will not be the correct value and can cause shifting on iOS.
> fix: iOS issues when header height is undefined

- src/Container.tsx
- src/helpers.tsx
- src/hooks.tsx
Pulling down to refresh does not seem to work on the Example app using Expo, when the tab pane is scrolled to the top.
This only seems to happen in that case though, in a bare RN iOS app everything seems fine.
This workaround creates other issue though, and isn't correct. We'll need to find a better solution.
> fix: remove ios scroll reset workaround

- src/Container.tsx
In reanimated 2 rc.0, `useSharedValue` actually recomputes the value and acts as `useDerivedValue` unless `false` is passed to the second parameter.
This can cause a glitch in the indicator mid-snap if the container needs to re-render.
> fix: indicator glitch because scrollX was being reset

- src/Container.tsx
> fix: assume headerHeight is 0 if HeaderComponent isn't provided

- example/src/Shared/Albums.tsx
- example/src/Shared/Article.tsx
- src/FlatList.tsx
- src/ScrollView.tsx
Add `<RefreshControl />` to FlatList and ScrollView. Helps to avoid call the `useCollapsibleStyle` on every refresh control.
> feat: support custom refresh control component

- example/src/Shared/QuickStartDemo.tsx
- src/Container.tsx
- src/FlatList.tsx
- src/MaterialTabBar/TabBar.tsx
- src/ScrollView.tsx
- src/hooks.tsx
- src/types.ts
This should greatly improve performance, especially with scrollable tab bars.
It also optimizes various other things, and reduces rerenders a bit.
It should be possible to test it by adding a `git` dependency directly:
```
"react-native-collapsible-tab-view": "PedroBern/react-native-collapsible-tab-view#perf-rerenders",
```
> perf: optimize and reduce rerenders

- .prettierrc.json
- README.md
- documentation/README_TEMPLATE.md
- documentation/buildDocs.ts
- example/App.tsx
- example/package.json
- example/src/MinHeaderHeight.tsx
- example/src/RevealHeaderOnScroll.tsx
- example/src/ScrollOnHeader.tsx
- example/src/Shared/Contacts.tsx
- example/src/Shared/ExampleComponent.tsx
- example/src/Shared/SectionContacts.tsx
- example/src/UndefinedHeaderHeight.tsx
- example/tsconfig.json
- example/yarn.lock
- package.json
- src/Container.tsx
- src/FlatList.tsx
- src/Lazy.tsx
- src/SectionList.tsx
- src/helpers.tsx
- src/index.tsx
- src/types.ts
- yarn.lock
Added SectionList Support. Also updated documentation and added example tab with a SectionList.
As we know from https://github.com/PedroBern/react-native-collapsible-tab-view/issues/136 stickyHeaders cause a problem. This issue also applies to SectionList. I played around with paddingTop, but couldn´t solve the issue.
I also upgraded Expo to v42 and reanimated to v2.2.2.
> feat: SectionList support (without stickyHeaders for now)

- README.md
- documentation/README_TEMPLATE.md
Change `useAnimatedTabIndex()` under useFocusedTab sub heading to the right method.
> docs: fix typo in to Readme

- README.md
- src/Container.tsx
- src/MaterialTabBar/TabBar.tsx
- src/MaterialTabBar/types.ts
- src/hooks.tsx
- src/types.ts
First of all, thank you for a really great library! It deals with some really hard to pull off user interactions!
In an app we're building we get an issue where the window width is miscalulated after having rotated from portrait to landscape and then back to portrait. React native's built in `useWindowDimensions` hook will still return the landscape width even if the app is rotated back to portrait mode. 
Our specific case is probably quite extraordinary, we actually switch between a portrait UIWindow to a landscape UIWindow and then back. And when we do we still get landscape width which causes parts of the tab view to render outside of the screen. When swiping between tabs the app will crash.
Replacing the `useWindowDimensions` hook with `useSafeAreaFrame` from …
> feat: add `width` prop to `Tabs.Container`

- README.md
- example/src/App.tsx
- example/src/HeaderOverscroll.tsx
- example/src/Shared/Header.tsx
- src/Container.tsx
- src/hooks.tsx
- src/types.ts
This implements a new property:
```ts
/**
* Whether the header moves down during overscrolling (for example on pull-to-refresh on iOS) or sticks to the top
*
* @default false
*/
allowHeaderOverscroll: boolean
```
It basically allows the header to move down while overscrolling on iOS so that the pull to refresh appears above the header rather than below.
Here's a video of what this does:
> feat: allow header to move down on pull to refresh on iOS

- src/hooks.tsx
> fix: edge case with tabs still scrolling to top

- CHANGELOG.md
- README.md
- documentation/README_TEMPLATE.md
- example/src/AnimatedHeader.tsx
- example/src/Shared/Contacts.tsx
- example/src/Shared/ReText.tsx
- example/src/Shared/SectionContacts.tsx
- package.json
- src/Container.tsx
- src/hooks.tsx
- src/index.tsx
Closes #263 
Closes #203 
BREAKING CHANGE: `useHeaderMeasurements` now returns
the `height` as an `Animated.SharedValue`
> feat: adds `useCurrentTabScrollY` hook

- example/src/Shared/ExampleComponentFlashList.tsx
- example/src/Shared/ExampleComponentMasonryFlashList.tsx
- src/FlashList.tsx
- src/MasonryFlashList.tsx
- src/hooks.tsx
> fix: lazy FlashList scroll sync issue

- example/src/ConditionalTabs.tsx
- example/src/DynamicTabs.tsx
- src/Container.tsx
- src/Lazy.tsx
- src/hooks.tsx
- src/types.ts
- yarn.lock
> fix: dynamic tab sync

- example/src/App.tsx
- example/src/Shared/ExampleComponentFlashList.tsx
- example/src/Shared/ExampleComponentMasonryFlashList.tsx
- example/src/SingleTab.tsx
- src/MaterialTabBar/Indicator.tsx
In my app I added some container style with padding to have a specific display for the tabs. When there is only one tab, the indicator is not shifted accordingly. This is due to the `itemsLayout.length > 1` condition and the `undefined` value of `transform`. The same way as it's done for the `width`, I changed the `transform` to match the first item of the `itemsLayout` array if there is only one tab.
<table>
<tr>
<th> Before
<th> After
<tr>
<td> <img src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/5436545/dd08ac8d-89ce-44c2-9366-384fa9cd483c">
<td> <img src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/5436545/d168c162-0cd8-4237-b5fa-5198d7af76ba">
</table>
> fix: indicator display for single tab

- example/src/AnimatedHeader.tsx
- example/src/FlashList.tsx
- example/src/MasonryFlashList.tsx
- example/src/Shared/Contacts.tsx
- example/src/Shared/ContactsFlashList.tsx
- example/src/Shared/ExampleMasonry.tsx
- example/src/Shared/SectionContacts.tsx
- src/Container.tsx
- src/FlashList.tsx
- src/FlatList.tsx
- src/Lazy.tsx
- src/MasonryFlashList.tsx
- src/ScrollView.tsx
- src/SectionList.tsx
- src/hooks.tsx
- src/types.ts
Hey  @andreialecu  and @gkartalis (tagging bc I can't add reviewers), I was introducing this library to solve a UI pattern and noticed blocking JavaScript thread behavior that caused a regression of over 500ms to our initial screen render. 
The flame graph above shows that the JavaScript thread is blocked by executeOnUIRuntimeSync for quite some time impacting the initial render time of a screen by over 500ms.
On closer analysis I found that the problem is caused by reading a SharedValue.value in the main JS thread. This library does this quite often in places that could avoid it. This PR refactors most of the places where it does not need to be a SharedValue while trying to not cause any regressions.
I understand there isn't unit or e2e tests for this library so I tried my best to test …
> refactor(container,lazy,hooks): avoid blocking JS thread by refactoring SharedValue.value access
