PedroBern/react-native-collapsible-tab-view

example/src/App.tsx, example/src/CollapsibleTabViewDemoExample.tsx, example/src/CollapsibleTabViewExample.tsx, example/src/CollapsibleTabViewNoSnapExample.tsx, example/src/CollapsibleTabViewNoUpfrontHeightExample.tsx, example/src/CollapsibleTabViewResizeExample.tsx, example/src/CollapsibleTabViewSmallContentExample.tsx, example/src/NavigationExample.tsx, src/CollapsibleTabView.tsx
=> Fix header not showing

example/src/App.tsx, example/src/CollapsibleTabViewCenteredEmptyListExample.tsx, example/src/Shared/AnimatedContext.tsx, example/src/Shared/Contacts.tsx, src/CollapsibleTabViewContext.tsx, src/index.tsx
=> docs: add centered empty list example

README.md, example/src/App.tsx, example/src/CollapsibleTabViewScrollOnHeaderExample.tsx, src/CollapsibleTabView.tsx
=> feat: scroll on header

example/src/App.tsx, example/src/CollapsibleTabViewNoHeaderExample.tsx, src/CollapsibleTabView.tsx
Please check whether it works.
=> feat: no header

README.md, example/src/App.tsx, example/src/Lazy.tsx, src/createCollapsibleTabs.tsx, src/types.ts
=> feat: add lazy support

src/createCollapsibleTabs.tsx
=> fix: prevent not updating translateY if not providing the headerHeight

README.md, example/src/App.tsx, example/src/UndefinedHeaderHeight.tsx, src/createCollapsibleTabs.tsx
=> feat: add fade-in if headerHeight is undefined

README.md, example/src/Shared/Albums.tsx, example/src/Shared/Article.tsx, example/src/Shared/Contacts.tsx, example/src/Shared/QuickStartDemo.tsx, src/createCollapsibleTabs.tsx, src/types.ts
Remove the need of name prop in scrollable components.
=> Feat tab name context

README.md, example/src/App.tsx, example/src/OnIndexChange.tsx, example/src/Ref.tsx, example/src/Shared/ExampleComponent.tsx, example/src/Shared/ExampleComponentScrollableTabs.tsx, example/src/Shared/Header.tsx, src/MaterialTabBar/TabBar.tsx, src/MaterialTabBar/index.tsx, src/MaterialTabBar/types.ts, src/createCollapsibleTabs.tsx, src/index.tsx, src/types.ts
fix #71 
fix #64
@alexpchin you gonna like this
=> feat: add imperactive ref handler + onChangeIndex

example/src/Shared/ExampleComponentScrollableTabs.tsx, src/MaterialTabBar/TabBar.tsx
=> feat: showing issue with scrollable-tabs

example/src/DynamicTabs.tsx, src/hooks.tsx
=> fix: conditional dynamic tabs

package.json, tsconfig.build.json
=> fix: exclude documentation from library build

README.md, documentation/README_TEMPLATE.md, example/src/AndroidSharedPullToRefresh.tsx, example/src/App.tsx, example/src/Shared/Contacts.tsx, example/src/Shared/ExampleComponent.tsx, example/src/Shared/ExampleComponentScrollableTabs.tsx, example/src/Shared/ExampleComponentSharedPullToRefresh.tsx, example/src/types.ts
=> Docs shared pull to refresh

src/FlatList.tsx, src/ScrollView.tsx
=> fix: content inset broken on react native

src/hooks.tsx
=> fix: ensure top line (1px) is visible on iOS

src/MaterialTabBar/TabBar.tsx
This fixes #109 
Although, I'm still not 100% sure why...
=> refactor: swapping to Array.from

src/Container.tsx, src/MaterialTabBar/TabBar.tsx
Memoize components to prevent some unnecessary re-renders
=> perf: memoize

README.md, documentation/README_TEMPLATE.md, example/src/AnimatedHeader.tsx, example/src/App.tsx, src/Container.tsx, src/hooks.tsx, src/index.tsx, src/types.ts
Todo: add some examples
(currently untested)
=> feat: expose hooks

example/src/App.tsx, example/src/Shared/Contacts.tsx, src/Container.tsx, src/FlatList.tsx, src/ScrollView.tsx, src/hooks.tsx, src/types.ts
=> fix: rework contentHeights to use a shared value

README.md, src/Container.tsx
The readme was missing the `Tabs.Container` api
=> docs: add missing Tabs.Container to docs

example/src/AnimatedHeader.tsx
=> fix: animated header example

package.json, src/Container.tsx, src/FlatList.tsx, src/SectionList.tsx, src/hooks.tsx
=> fix: tabs should not scroll to top

src/Container.tsx
This should fix https://github.com/PedroBern/react-native-collapsible-tab-view/issues/411
=> fix: tabs not being displayed on Android
